github: [b-fuze, sinnx3]
ko_fi: sinnx3
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.blockchain.com/btc/address/3GpMJhF8r1ZP6ZLBJMhRXNSLkibiJbR6da', 'https://www.blockchain.com/eth/address/0x79a895073dda4b6a511173fb545532Dd33e3A92E']
